import https from 'https';
import fs from 'fs';
import path from 'path';

const options = {
  hostname: 'www.sec.gov',
  path: '/files/company_tickers.json',
  headers: {
    'User-Agent': 'Mozilla/5.0'
  }
};

https.get(options, (res) => {
  let data = '';
  res.on('data', (chunk) => { data += chunk; });
  res.on('end', () => {
    try {
      const parsed = JSON.parse(data);
      const tickers = Object.values(parsed).map((v: any) => v.ticker);
      // Remove duplicates
      const uniqueTickers = Array.from(new Set(tickers));
      
      const tsCode = `// Autogenerated
import { AssetType } from './types';

export const EXTENDED_TICKERS = [
` + uniqueTickers.map((t: string) => `  { key: '${t}', ticker: '${t}', name: '${t} Stock', type: 'STOCKS' as AssetType, defaultPrice: ${Math.round(Math.random() * 200 + 10)}, decimals: 2, spread: 0.02, volatility: 0.8, unit: 'USD', forecastScale: 0.1, stabilityMax: 0.05, optionsStyle: 'weekly' }`).join(',\n') + `
];
`;
      fs.writeFileSync(path.join(process.cwd(), 'src/extended_tickers.ts'), tsCode);
      console.log('Saved ' + uniqueTickers.length + ' tickers');
    } catch (e) {
      console.error(e);
      fallback();
    }
  });
}).on('error', (err) => {
  console.error(err);
  fallback();
});

function fallback() {
  console.log('Using fallback...');
  let tickers = [];
  for(let i=0; i<6500; i++) {
    tickers.push('TICK' + i);
  }
  const tsCode = `import { AssetType } from './types';

export const EXTENDED_TICKERS = [
` + tickers.map((t) => `  { key: '${t}', ticker: '${t}', name: '${t} Stock', type: 'STOCKS' as AssetType, defaultPrice: 100, decimals: 2, spread: 0.02, volatility: 0.8, unit: 'USD', forecastScale: 0.1, stabilityMax: 0.05, optionsStyle: 'weekly' }`).join(',\n') + `
];
`;
  fs.writeFileSync(path.join(process.cwd(), 'src/extended_tickers.ts'), tsCode);
}
